name: kabja
description: Run. Capture. Dominate.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.5
  app_links: ^6.4.1
  h3_flutter: ^0.6.6
  google_fonts: ^6.3.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  lottie: ^3.3.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
